url: ''
baseurl: ''
#title: "Binary Bard: Navigating the Nexus of Nerdom"
title: "Jordan's Tech Nerdom"
profile_image: https://gravatar.com/avatar/c47502b47b66f286b7df9b811a0aceb5da9c3a45ba166eb35e000ec72d64445a?s=600
logo: bbnnn-logo.png
social:
  twitter_username: jmwamser
  github_username: jmwamser
  mastodon:
    - username: RedPHPandaBytes
      instance: phpc.social
  facebook_username: wamserjm
  instagram_username:
  linkedin_username: jwamser
  pinterest_username:
  rss:


plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
